### ISSUE TITLE
minor typo in POD

### ISSUE THREAD

**Issue by fschlich** [ronsavage/CGI-Session-ExpireSessions#1]
contructor -> constructor in lib/CGI/Session/ExpireSessions.pm v1.14

I would have sent a pull request, but this repo is empty...

**Comment by ronsavage** [comment]
Hi Florian

Thanx for the report. You were right, the repo was empty, probably 
because back in 2010 I wrote Data::Session to replace CGI::Session, to 
go with my CGI::Snapp (2012) which was designed to replace CGI::Session.

Anyway, I adopted your correction, and have just uploaded the patch to 
github. But, for such a small patch my policy is to not bother releasing 
another version to CPAN. I just prefer users switch to the new code.

---
Cheers
Ron
savage.net.au

**Comment by fschlich** [comment]
Hi Ron,

I think you're perfectly right not to upload a release for such an insignificant change. From my perspective, I want the issue off my mind: the fix is where it belongs, and it won't be forgotten next time things happen - perfect!

Thanks, Florian
